CREATE DATABASE sye_db default CHARACTER SET UTF8;
USE sye_db;

CREATE TABLE PLAYLIST
(
    PLAYLIST_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
    PLAYLIST_NAME VARCHAR(30) NOT NULL,
    PLAYLIST_THUMBNAIL VARCHAR(255)
);

CREATE TABLE SONGINFO
(
    SONGINFO_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
    SONGINFO_NAME VARCHAR(30) NOT NULL,
    SONGINFO_SINGER VARCHAR(30) NOT NULL,
    SONGINFO_ALBUMURL VARCHAR(255),
    SONGINFO_ALBUM VARCHAR(30) NOT NULL,
    PLAYLIST_NUMBER BIGINT NOT NULL
);

ALTER TABLE SONGINFO ADD FOREIGN KEY(PLAYLIST_NUMBER) REFERENCES PLAYLIST(PLAYLIST_NUMBER) ON DELETE CASCADE;
