CREATE DATABASE sye_db default CHARACTER SET UTF8;
USE sye_db;

CREATE TABLE PLAYLIST
(
    PLAYLIST_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
    PLAYLIST_NAME VARCHAR(30) NOT NULL,
    PLAYLIST_FOLLOW INT DEFAULT 0
);

CREATE TABLE SONGINFO
(
    SONGINFO_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
    SONGINFO_NAME VARCHAR(30) NOT NULL,
    SONGINFO_SINGER VARCHAR(30) NOT NULL,
    SONGINFO_ALBUMURL VARCHAR(255),
    SONGINFO_ALBUM VARCHAR(30) NOT NULL,
    SONGINFO_TIME VARCHAR(30) NOT NULL,
    PLAYLIST_NUMBER BIGINT NOT NULL
);

ALTER TABLE SONGINFO ADD FOREIGN KEY(PLAYLIST_NUMBER) REFERENCES PLAYLIST(PLAYLIST_NUMBER);

CREATE TABLE DUMMY1
(
    D1_TITLE VARCHAR(30) NOT NULL,
    D1_SINGER VARCHAR(30) NOT NULL,
    D1_ALBUMURL VARCHAR(255) NOT NULL,
    D1_ALBUM VARCHAR(30) NOT NULL,
    D1_TIME VARCHAR(30) NOT NULL,
);

CREATE TABLE DUMMY2
(
    D2_TITLE VARCHAR(30) NOT NULL,
    D2_SINGER VARCHAR(30) NOT NULL,
    D2_ALBUMURL VARCHAR(255) NOT NULL,
    D2_ALBUM VARCHAR(30) NOT NULL,
    D2_TIME VARCHAR(30) NOT NULL,
);
