# PLAYLIST 테이블 테스트용 더미데이터
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('FIRST', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/FIRST.jpg?alt=media');
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('SECOND', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/SECOND.jpg?alt=media');
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('THIRD', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/THIRD.jpg?alt=media');
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('FOURTH', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/FOURTH.jpg?alt=media');
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('FIFTH', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/FIFTH.jpg?alt=media');
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('SIXTH', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/SIXTH.jpg?alt=media');
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('SEVENTH', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/SEVENTH.jpg?alt=media');
INSERT INTO PLAYLIST(PLAYLIST_NAME, PLAYLIST_THUMBNAIL) VALUES ('EIGHTH', 'https://firebasestorage.googleapis.com/v0/b/sye-image.appspot.com/o/EIGHTH.jpg?alt=media');



# SONGINFO 테이블 테스트용 더미데이터1
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('라일락', '아이유', 'LILAC', '3:34', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Flu', '아이유', 'LILAC', '3:03', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Coin', '아이유', 'LILAC', '3:13', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('봄 안녕 봄', '아이유', 'LILAC', '5:24', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Celebrity', '아이유', 'LILAC', '3:15', 1);




# SONGINFO 테이블 테스트용 더미데이터2
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('나들이 갈까', '볼빨간사춘기', '사춘기집I 꽃기운', '3:05', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('나만, 봄', '볼빨간사춘기', '사춘기집I 꽃기운', '3:37', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('별 보러 갈래?', '볼빨간사춘기', '사춘기집I 꽃기운', '3:21', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Seattle Alone', '볼빨간사춘기', '사춘기집I 꽃기운', '3:34', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Mermaid', '볼빨간사춘기', '사춘기집I 꽃기운', '4:57', 2);




# SONGINFO 테이블 테스트용 더미데이터3
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('PARADE', '윤하', 'RescuE', '3:14', 3);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('I Believe', '윤하', '신데렐라와 네 명의 기사들, Pt. 5', '3:32', 3);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('오르트구름', '윤하', 'END THEORY', '3:27', 3);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('WINTER FLOWER', '윤하', 'UNSTABLE MINDSET', '3:42', 3);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('비밀번호 486', '윤하', '고백하기 좋은 날', '3:49', 3);




# SONGINFO 테이블 테스트용 더미데이터4
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('나비효과', '볼빨간사춘기', 'Butterfly Effect', '3:27', 4);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('비와 당신', '이무진', '슬기로운 의사생활 시즌2 OST Part 1', '4:22', 4);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('먹구름', '윤하', 'UNSTABLE MINDSET', '4:00', 4);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('주저하는 연인들을 위해', 'JANNABI', '전설', '4:25', 4);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('TOMBOY', 'HYUKOH', '23', '4:01', 4);




# SONGINFO 테이블 테스트용 더미데이터5
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('째깍 째깍 째깍', 'AKMU', 'NEXT EPISODE', '3:57', 5);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('화장을 하고', '이보람 및 김연지', '화장을 하고', '3:44', 5);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Starlight', '소향', '퍼퓸 OST Part.2', '3:53', 5);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('바람기억', '나얼', 'Principle Of My Soul', '5:09', 5);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Insomnia', '유키카', 'timeabout', '3:28', 5);




# SONGINFO 테이블 테스트용 더미데이터6
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('덤덤해지네 Be Calm (Hwa Sa Solo)', 'MAMAMOO 및 Hwa Sa', 'Yellow Flower', '3:28', 6);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Sunflower', '윤하', '닥터스 OST Part. 2', '3:31', 6);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('My Last Love: In Paradisum', '에일리', '시지프스', '4:19', 6);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('서로의 눈물이 되어', '효린', '화랑, Pt. 5', '4:23', 6);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Fade Away', '거미', '100 DAYS MY PRINCE', '3:52', 6);




# SONGINFO 테이블 테스트용 더미데이터7
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('애쓰지 마요', 'Park Boram', '애쓰지 마요', '3:49', 7);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('우릴 사랑으로 기억해줘요(feat. 정소안)', '새봄(saevom)', '우릴 사랑으로 기억해줘요', '4:35', 7);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('이럴거면 그러지말지', '백아연', '이럴거면 그러지말지', '3:32', 7);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Tick-Tock', '신지훈', '퍼퓸 OST Part.9', '3:41', 7);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('오늘밤도', '펀치', '오늘밤도', '3:09', 7);




# SONGINFO 테이블 테스트용 더미데이터8
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('시간을 거슬러', '린', '해를 품은 달 OST Part.2', '3:32', 8);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Love Story', '린', '푸른 바다의 전설 OST Part.1', '3:31', 8);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Another Day', '먼데이키즈 및 펀치', '호텔 델루나 OST', '3:38', 8);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('아직 너의 시간에 살아', '이수현', '사이코지만 괜찮아 OST', '4:29', 8);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('노래가 늘었어', '에일리', '노래가 늘었어', '3:20', 8);





