# PLAYLIST 테이블 테스트용 더미데이터
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('FIRST');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('SECOND');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('THIRD');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('FOURTH');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('FIFTH');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('SIXTH');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('SEVENTH');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('EIGHTH');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('NINETH');
INSERT INTO PLAYLIST(PLAYLIST_NAME) VALUES ('TENTH');


# SONGINFO 테이블 테스트용 더미데이터1
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('라일락', '아이유', 'LILAC', '3:34', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Flu', '아이유', 'LILAC', '3:03', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Coin', '아이유', 'LILAC', '3:13', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('봄 안녕 봄', '아이유', 'LILAC', '5:24', 1);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Celebrity', '아이유', 'LILAC', '3:15', 1);



# SONGINFO 테이블 테스트용 더미데이터2
INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('나들이 갈까', '볼빨간사춘기', '사춘기집I 꽃기운', '3:05', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('나만, 봄', '볼빨간사춘기', '사춘기집I 꽃기운', '3:37', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('별 보러 갈래?', '볼빨간사춘기', '사춘기집I 꽃기운', '3:21', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Seattle Alone', '볼빨간사춘기', '사춘기집I 꽃기운', '3:34', 2);

INSERT INTO SONGINFO(SONGINFO_NAME, SONGINFO_SINGER, SONGINFO_ALBUM, SONGINFO_TIME, PLAYLIST_NUMBER)
VALUES ('Mermaid', '볼빨간사춘기', '사춘기집I 꽃기운', '4:57', 2);

# SONGINFO 테이블 테스트용 더미데이터3
# SONGINFO 테이블 테스트용 더미데이터4
# SONGINFO 테이블 테스트용 더미데이터5
